-- Auto-generated regions seed
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE region;

INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (1, 'Chattagram', 'Division', NULL);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (2, 'Rajshahi', 'Division', NULL);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (3, 'Khulna', 'Division', NULL);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (4, 'Barisal', 'Division', NULL);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (5, 'Sylhet', 'Division', NULL);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (6, 'Dhaka', 'Division', NULL);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (7, 'Rangpur', 'Division', NULL);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (8, 'Mymensingh', 'Division', NULL);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (9, 'Comilla', 'District', 1);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (10, 'Feni', 'District', 1);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (11, 'Brahmanbaria', 'District', 1);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (12, 'Rangamati', 'District', 1);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (13, 'Noakhali', 'District', 1);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (14, 'Chandpur', 'District', 1);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (15, 'Lakshmipur', 'District', 1);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (16, 'Chattogram', 'District', 1);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (17, 'Coxsbazar', 'District', 1);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (18, 'Khagrachhari', 'District', 1);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (19, 'Bandarban', 'District', 1);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (20, 'Sirajganj', 'District', 2);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (21, 'Pabna', 'District', 2);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (22, 'Bogura', 'District', 2);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (23, 'Rajshahi', 'District', 2);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (24, 'Natore', 'District', 2);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (25, 'Joypurhat', 'District', 2);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (26, 'Chapainawabganj', 'District', 2);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (27, 'Naogaon', 'District', 2);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (28, 'Jashore', 'District', 3);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (29, 'Satkhira', 'District', 3);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (30, 'Meherpur', 'District', 3);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (31, 'Narail', 'District', 3);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (32, 'Chuadanga', 'District', 3);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (33, 'Kushtia', 'District', 3);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (34, 'Magura', 'District', 3);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (35, 'Khulna', 'District', 3);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (36, 'Bagerhat', 'District', 3);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (37, 'Jhenaidah', 'District', 3);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (38, 'Jhalakathi', 'District', 4);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (39, 'Patuakhali', 'District', 4);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (40, 'Pirojpur', 'District', 4);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (41, 'Barisal', 'District', 4);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (42, 'Bhola', 'District', 4);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (43, 'Barguna', 'District', 4);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (44, 'Sylhet', 'District', 5);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (45, 'Moulvibazar', 'District', 5);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (46, 'Habiganj', 'District', 5);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (47, 'Sunamganj', 'District', 5);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (48, 'Narsingdi', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (49, 'Gazipur', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (50, 'Shariatpur', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (51, 'Narayanganj', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (52, 'Tangail', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (53, 'Kishoreganj', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (54, 'Manikganj', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (55, 'Dhaka', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (56, 'Munshiganj', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (57, 'Rajbari', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (58, 'Madaripur', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (59, 'Gopalganj', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (60, 'Faridpur', 'District', 6);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (61, 'Panchagarh', 'District', 7);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (62, 'Dinajpur', 'District', 7);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (63, 'Lalmonirhat', 'District', 7);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (64, 'Nilphamari', 'District', 7);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (65, 'Gaibandha', 'District', 7);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (66, 'Thakurgaon', 'District', 7);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (67, 'Rangpur', 'District', 7);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (68, 'Kurigram', 'District', 7);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (69, 'Sherpur', 'District', 8);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (70, 'Mymensingh', 'District', 8);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (71, 'Jamalpur', 'District', 8);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (72, 'Netrokona', 'District', 8);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (73, 'Debidwar', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (74, 'Barura', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (75, 'Brahmanpara', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (76, 'Chandina', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (77, 'Chauddagram', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (78, 'Daudkandi', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (79, 'Homna', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (80, 'Laksam', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (81, 'Muradnagar', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (82, 'Nangalkot', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (83, 'Comilla Sadar', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (84, 'Meghna', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (85, 'Monohargonj', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (86, 'Sadarsouth', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (87, 'Titas', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (88, 'Burichang', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (89, 'Lalmai', 'Sub-district', 9);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (90, 'Chhagalnaiya', 'Sub-district', 10);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (91, 'Feni Sadar', 'Sub-district', 10);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (92, 'Sonagazi', 'Sub-district', 10);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (93, 'Fulgazi', 'Sub-district', 10);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (94, 'Parshuram', 'Sub-district', 10);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (95, 'Daganbhuiyan', 'Sub-district', 10);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (96, 'Brahmanbaria Sadar', 'Sub-district', 11);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (97, 'Kasba', 'Sub-district', 11);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (98, 'Nasirnagar', 'Sub-district', 11);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (99, 'Sarail', 'Sub-district', 11);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (100, 'Ashuganj', 'Sub-district', 11);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (101, 'Akhaura', 'Sub-district', 11);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (102, 'Nabinagar', 'Sub-district', 11);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (103, 'Bancharampur', 'Sub-district', 11);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (104, 'Bijoynagar', 'Sub-district', 11);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (105, 'Rangamati Sadar', 'Sub-district', 12);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (106, 'Kaptai', 'Sub-district', 12);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (107, 'Kawkhali', 'Sub-district', 12);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (108, 'Baghaichari', 'Sub-district', 12);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (109, 'Barkal', 'Sub-district', 12);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (110, 'Langadu', 'Sub-district', 12);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (111, 'Rajasthali', 'Sub-district', 12);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (112, 'Belaichari', 'Sub-district', 12);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (113, 'Juraichari', 'Sub-district', 12);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (114, 'Naniarchar', 'Sub-district', 12);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (115, 'Noakhali Sadar', 'Sub-district', 13);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (116, 'Companiganj', 'Sub-district', 13);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (117, 'Begumganj', 'Sub-district', 13);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (118, 'Hatia', 'Sub-district', 13);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (119, 'Subarnachar', 'Sub-district', 13);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (120, 'Kabirhat', 'Sub-district', 13);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (121, 'Senbug', 'Sub-district', 13);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (122, 'Chatkhil', 'Sub-district', 13);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (123, 'Sonaimori', 'Sub-district', 13);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (124, 'Haimchar', 'Sub-district', 14);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (125, 'Kachua', 'Sub-district', 14);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (126, 'Shahrasti', 'Sub-district', 14);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (127, 'Chandpur Sadar', 'Sub-district', 14);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (128, 'Matlab South', 'Sub-district', 14);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (129, 'Hajiganj', 'Sub-district', 14);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (130, 'Matlab North', 'Sub-district', 14);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (131, 'Faridgonj', 'Sub-district', 14);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (132, 'Lakshmipur Sadar', 'Sub-district', 15);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (133, 'Kamalnagar', 'Sub-district', 15);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (134, 'Raipur', 'Sub-district', 15);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (135, 'Ramgati', 'Sub-district', 15);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (136, 'Ramganj', 'Sub-district', 15);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (137, 'Rangunia', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (138, 'Sitakunda', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (139, 'Mirsharai', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (140, 'Patiya', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (141, 'Sandwip', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (142, 'Banshkhali', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (143, 'Boalkhali', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (144, 'Anwara', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (145, 'Chandanaish', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (146, 'Satkania', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (147, 'Lohagara', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (148, 'Hathazari', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (149, 'Fatikchhari', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (150, 'Raozan', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (151, 'Karnafuli', 'Sub-district', 16);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (152, 'Coxsbazar Sadar', 'Sub-district', 17);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (153, 'Chakaria', 'Sub-district', 17);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (154, 'Kutubdia', 'Sub-district', 17);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (155, 'Ukhiya', 'Sub-district', 17);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (156, 'Moheshkhali', 'Sub-district', 17);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (157, 'Pekua', 'Sub-district', 17);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (158, 'Ramu', 'Sub-district', 17);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (159, 'Teknaf', 'Sub-district', 17);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (160, 'Khagrachhari Sadar', 'Sub-district', 18);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (161, 'Dighinala', 'Sub-district', 18);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (162, 'Panchari', 'Sub-district', 18);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (163, 'Laxmichhari', 'Sub-district', 18);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (164, 'Mohalchari', 'Sub-district', 18);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (165, 'Manikchari', 'Sub-district', 18);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (166, 'Ramgarh', 'Sub-district', 18);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (167, 'Matiranga', 'Sub-district', 18);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (168, 'Guimara', 'Sub-district', 18);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (169, 'Bandarban Sadar', 'Sub-district', 19);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (170, 'Alikadam', 'Sub-district', 19);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (171, 'Naikhongchhari', 'Sub-district', 19);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (172, 'Rowangchhari', 'Sub-district', 19);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (173, 'Lama', 'Sub-district', 19);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (174, 'Ruma', 'Sub-district', 19);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (175, 'Thanchi', 'Sub-district', 19);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (176, 'Belkuchi', 'Sub-district', 20);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (177, 'Chauhali', 'Sub-district', 20);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (178, 'Kamarkhand', 'Sub-district', 20);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (179, 'Kazipur', 'Sub-district', 20);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (180, 'Raigonj', 'Sub-district', 20);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (181, 'Shahjadpur', 'Sub-district', 20);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (182, 'Sirajganj Sadar', 'Sub-district', 20);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (183, 'Tarash', 'Sub-district', 20);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (184, 'Ullapara', 'Sub-district', 20);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (185, 'Sujanagar', 'Sub-district', 21);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (186, 'Ishurdi', 'Sub-district', 21);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (187, 'Bhangura', 'Sub-district', 21);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (188, 'Pabna Sadar', 'Sub-district', 21);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (189, 'Bera', 'Sub-district', 21);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (190, 'Atghoria', 'Sub-district', 21);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (191, 'Chatmohar', 'Sub-district', 21);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (192, 'Santhia', 'Sub-district', 21);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (193, 'Faridpur', 'Sub-district', 21);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (194, 'Kahaloo', 'Sub-district', 22);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (195, 'Bogra Sadar', 'Sub-district', 22);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (196, 'Shariakandi', 'Sub-district', 22);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (197, 'Shajahanpur', 'Sub-district', 22);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (198, 'Dupchanchia', 'Sub-district', 22);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (199, 'Adamdighi', 'Sub-district', 22);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (200, 'Nondigram', 'Sub-district', 22);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (201, 'Sonatala', 'Sub-district', 22);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (202, 'Dhunot', 'Sub-district', 22);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (203, 'Gabtali', 'Sub-district', 22);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (204, 'Sherpur', 'Sub-district', 22);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (205, 'Shibganj', 'Sub-district', 22);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (206, 'Paba', 'Sub-district', 23);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (207, 'Durgapur', 'Sub-district', 23);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (208, 'Mohonpur', 'Sub-district', 23);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (209, 'Charghat', 'Sub-district', 23);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (210, 'Puthia', 'Sub-district', 23);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (211, 'Bagha', 'Sub-district', 23);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (212, 'Godagari', 'Sub-district', 23);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (213, 'Tanore', 'Sub-district', 23);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (214, 'Bagmara', 'Sub-district', 23);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (215, 'Natore Sadar', 'Sub-district', 24);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (216, 'Singra', 'Sub-district', 24);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (217, 'Baraigram', 'Sub-district', 24);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (218, 'Bagatipara', 'Sub-district', 24);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (219, 'Lalpur', 'Sub-district', 24);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (220, 'Gurudaspur', 'Sub-district', 24);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (221, 'Naldanga', 'Sub-district', 24);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (222, 'Akkelpur', 'Sub-district', 25);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (223, 'Kalai', 'Sub-district', 25);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (224, 'Khetlal', 'Sub-district', 25);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (225, 'Panchbibi', 'Sub-district', 25);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (226, 'Joypurhat Sadar', 'Sub-district', 25);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (227, 'Chapainawabganj Sadar', 'Sub-district', 26);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (228, 'Gomostapur', 'Sub-district', 26);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (229, 'Nachol', 'Sub-district', 26);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (230, 'Bholahat', 'Sub-district', 26);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (231, 'Shibganj', 'Sub-district', 26);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (232, 'Mohadevpur', 'Sub-district', 27);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (233, 'Badalgachi', 'Sub-district', 27);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (234, 'Patnitala', 'Sub-district', 27);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (235, 'Dhamoirhat', 'Sub-district', 27);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (236, 'Niamatpur', 'Sub-district', 27);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (237, 'Manda', 'Sub-district', 27);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (238, 'Atrai', 'Sub-district', 27);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (239, 'Raninagar', 'Sub-district', 27);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (240, 'Naogaon Sadar', 'Sub-district', 27);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (241, 'Porsha', 'Sub-district', 27);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (242, 'Sapahar', 'Sub-district', 27);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (243, 'Manirampur', 'Sub-district', 28);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (244, 'Abhaynagar', 'Sub-district', 28);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (245, 'Bagherpara', 'Sub-district', 28);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (246, 'Chougachha', 'Sub-district', 28);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (247, 'Jhikargacha', 'Sub-district', 28);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (248, 'Keshabpur', 'Sub-district', 28);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (249, 'Jessore Sadar', 'Sub-district', 28);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (250, 'Sharsha', 'Sub-district', 28);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (251, 'Assasuni', 'Sub-district', 29);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (252, 'Debhata', 'Sub-district', 29);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (253, 'Kalaroa', 'Sub-district', 29);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (254, 'Satkhira Sadar', 'Sub-district', 29);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (255, 'Shyamnagar', 'Sub-district', 29);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (256, 'Tala', 'Sub-district', 29);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (257, 'Kaliganj', 'Sub-district', 29);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (258, 'Mujibnagar', 'Sub-district', 30);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (259, 'Meherpur Sadar', 'Sub-district', 30);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (260, 'Gangni', 'Sub-district', 30);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (261, 'Narail Sadar', 'Sub-district', 31);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (262, 'Lohagara', 'Sub-district', 31);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (263, 'Kalia', 'Sub-district', 31);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (264, 'Chuadanga Sadar', 'Sub-district', 32);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (265, 'Alamdanga', 'Sub-district', 32);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (266, 'Damurhuda', 'Sub-district', 32);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (267, 'Jibannagar', 'Sub-district', 32);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (268, 'Kushtia Sadar', 'Sub-district', 33);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (269, 'Kumarkhali', 'Sub-district', 33);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (270, 'Khoksa', 'Sub-district', 33);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (271, 'Mirpur', 'Sub-district', 33);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (272, 'Daulatpur', 'Sub-district', 33);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (273, 'Bheramara', 'Sub-district', 33);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (274, 'Shalikha', 'Sub-district', 34);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (275, 'Sreepur', 'Sub-district', 34);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (276, 'Magura Sadar', 'Sub-district', 34);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (277, 'Mohammadpur', 'Sub-district', 34);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (278, 'Paikgasa', 'Sub-district', 35);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (279, 'Fultola', 'Sub-district', 35);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (280, 'Digholia', 'Sub-district', 35);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (281, 'Rupsha', 'Sub-district', 35);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (282, 'Terokhada', 'Sub-district', 35);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (283, 'Dumuria', 'Sub-district', 35);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (284, 'Botiaghata', 'Sub-district', 35);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (285, 'Dakop', 'Sub-district', 35);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (286, 'Koyra', 'Sub-district', 35);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (287, 'Fakirhat', 'Sub-district', 36);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (288, 'Bagerhat Sadar', 'Sub-district', 36);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (289, 'Mollahat', 'Sub-district', 36);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (290, 'Sarankhola', 'Sub-district', 36);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (291, 'Rampal', 'Sub-district', 36);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (292, 'Morrelganj', 'Sub-district', 36);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (293, 'Kachua', 'Sub-district', 36);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (294, 'Mongla', 'Sub-district', 36);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (295, 'Chitalmari', 'Sub-district', 36);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (296, 'Jhenaidah Sadar', 'Sub-district', 37);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (297, 'Shailkupa', 'Sub-district', 37);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (298, 'Harinakundu', 'Sub-district', 37);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (299, 'Kaliganj', 'Sub-district', 37);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (300, 'Kotchandpur', 'Sub-district', 37);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (301, 'Moheshpur', 'Sub-district', 37);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (302, 'Jhalakathi Sadar', 'Sub-district', 38);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (303, 'Kathalia', 'Sub-district', 38);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (304, 'Nalchity', 'Sub-district', 38);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (305, 'Rajapur', 'Sub-district', 38);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (306, 'Bauphal', 'Sub-district', 39);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (307, 'Patuakhali Sadar', 'Sub-district', 39);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (308, 'Dumki', 'Sub-district', 39);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (309, 'Dashmina', 'Sub-district', 39);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (310, 'Kalapara', 'Sub-district', 39);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (311, 'Mirzaganj', 'Sub-district', 39);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (312, 'Galachipa', 'Sub-district', 39);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (313, 'Rangabali', 'Sub-district', 39);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (314, 'Pirojpur Sadar', 'Sub-district', 40);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (315, 'Nazirpur', 'Sub-district', 40);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (316, 'Kawkhali', 'Sub-district', 40);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (317, 'Zianagar', 'Sub-district', 40);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (318, 'Bhandaria', 'Sub-district', 40);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (319, 'Mathbaria', 'Sub-district', 40);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (320, 'Nesarabad', 'Sub-district', 40);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (321, 'Barisal Sadar', 'Sub-district', 41);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (322, 'Bakerganj', 'Sub-district', 41);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (323, 'Babuganj', 'Sub-district', 41);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (324, 'Wazirpur', 'Sub-district', 41);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (325, 'Banaripara', 'Sub-district', 41);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (326, 'Gournadi', 'Sub-district', 41);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (327, 'Agailjhara', 'Sub-district', 41);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (328, 'Mehendiganj', 'Sub-district', 41);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (329, 'Muladi', 'Sub-district', 41);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (330, 'Hizla', 'Sub-district', 41);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (331, 'Bhola Sadar', 'Sub-district', 42);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (332, 'Borhan Sddin', 'Sub-district', 42);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (333, 'Charfesson', 'Sub-district', 42);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (334, 'Doulatkhan', 'Sub-district', 42);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (335, 'Monpura', 'Sub-district', 42);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (336, 'Tazumuddin', 'Sub-district', 42);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (337, 'Lalmohan', 'Sub-district', 42);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (338, 'Amtali', 'Sub-district', 43);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (339, 'Barguna Sadar', 'Sub-district', 43);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (340, 'Betagi', 'Sub-district', 43);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (341, 'Bamna', 'Sub-district', 43);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (342, 'Pathorghata', 'Sub-district', 43);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (343, 'Taltali', 'Sub-district', 43);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (344, 'Balaganj', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (345, 'Beanibazar', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (346, 'Bishwanath', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (347, 'Companiganj', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (348, 'Fenchuganj', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (349, 'Golapganj', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (350, 'Gowainghat', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (351, 'Jaintiapur', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (352, 'Kanaighat', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (353, 'Sylhet Sadar', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (354, 'Zakiganj', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (355, 'Dakshinsurma', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (356, 'Osmaninagar', 'Sub-district', 44);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (357, 'Barlekha', 'Sub-district', 45);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (358, 'Kamolganj', 'Sub-district', 45);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (359, 'Kulaura', 'Sub-district', 45);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (360, 'Moulvibazar Sadar', 'Sub-district', 45);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (361, 'Rajnagar', 'Sub-district', 45);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (362, 'Sreemangal', 'Sub-district', 45);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (363, 'Juri', 'Sub-district', 45);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (364, 'Nabiganj', 'Sub-district', 46);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (365, 'Bahubal', 'Sub-district', 46);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (366, 'Ajmiriganj', 'Sub-district', 46);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (367, 'Baniachong', 'Sub-district', 46);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (368, 'Lakhai', 'Sub-district', 46);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (369, 'Chunarughat', 'Sub-district', 46);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (370, 'Habiganj Sadar', 'Sub-district', 46);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (371, 'Madhabpur', 'Sub-district', 46);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (372, 'Sunamganj Sadar', 'Sub-district', 47);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (373, 'South Sunamganj', 'Sub-district', 47);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (374, 'Bishwambarpur', 'Sub-district', 47);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (375, 'Chhatak', 'Sub-district', 47);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (376, 'Jagannathpur', 'Sub-district', 47);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (377, 'Dowarabazar', 'Sub-district', 47);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (378, 'Tahirpur', 'Sub-district', 47);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (379, 'Dharmapasha', 'Sub-district', 47);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (380, 'Jamalganj', 'Sub-district', 47);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (381, 'Shalla', 'Sub-district', 47);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (382, 'Derai', 'Sub-district', 47);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (383, 'Belabo', 'Sub-district', 48);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (384, 'Monohardi', 'Sub-district', 48);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (385, 'Narsingdi Sadar', 'Sub-district', 48);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (386, 'Palash', 'Sub-district', 48);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (387, 'Raipura', 'Sub-district', 48);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (388, 'Shibpur', 'Sub-district', 48);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (389, 'Kaliganj', 'Sub-district', 49);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (390, 'Kaliakair', 'Sub-district', 49);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (391, 'Kapasia', 'Sub-district', 49);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (392, 'Gazipur Sadar', 'Sub-district', 49);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (393, 'Sreepur', 'Sub-district', 49);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (394, 'Shariatpur Sadar', 'Sub-district', 50);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (395, 'Naria', 'Sub-district', 50);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (396, 'Zajira', 'Sub-district', 50);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (397, 'Gosairhat', 'Sub-district', 50);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (398, 'Bhedarganj', 'Sub-district', 50);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (399, 'Damudya', 'Sub-district', 50);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (400, 'Araihazar', 'Sub-district', 51);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (401, 'Bandar', 'Sub-district', 51);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (402, 'Narayanganj Sadar', 'Sub-district', 51);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (403, 'Rupganj', 'Sub-district', 51);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (404, 'Sonargaon', 'Sub-district', 51);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (405, 'Basail', 'Sub-district', 52);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (406, 'Bhuapur', 'Sub-district', 52);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (407, 'Delduar', 'Sub-district', 52);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (408, 'Ghatail', 'Sub-district', 52);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (409, 'Gopalpur', 'Sub-district', 52);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (410, 'Madhupur', 'Sub-district', 52);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (411, 'Mirzapur', 'Sub-district', 52);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (412, 'Nagarpur', 'Sub-district', 52);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (413, 'Sakhipur', 'Sub-district', 52);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (414, 'Tangail Sadar', 'Sub-district', 52);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (415, 'Kalihati', 'Sub-district', 52);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (416, 'Dhanbari', 'Sub-district', 52);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (417, 'Itna', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (418, 'Katiadi', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (419, 'Bhairab', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (420, 'Tarail', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (421, 'Hossainpur', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (422, 'Pakundia', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (423, 'Kuliarchar', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (424, 'Kishoreganj Sadar', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (425, 'Karimgonj', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (426, 'Bajitpur', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (427, 'Austagram', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (428, 'Mithamoin', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (429, 'Nikli', 'Sub-district', 53);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (430, 'Harirampur', 'Sub-district', 54);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (431, 'Saturia', 'Sub-district', 54);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (432, 'Manikganj Sadar', 'Sub-district', 54);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (433, 'Gior', 'Sub-district', 54);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (434, 'Shibaloy', 'Sub-district', 54);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (435, 'Doulatpur', 'Sub-district', 54);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (436, 'Singiar', 'Sub-district', 54);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (437, 'Savar', 'Sub-district', 55);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (438, 'Dhamrai', 'Sub-district', 55);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (439, 'Keraniganj', 'Sub-district', 55);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (440, 'Nawabganj', 'Sub-district', 55);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (441, 'Dohar', 'Sub-district', 55);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (442, 'Munshiganj Sadar', 'Sub-district', 56);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (443, 'Sreenagar', 'Sub-district', 56);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (444, 'Sirajdikhan', 'Sub-district', 56);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (445, 'Louhajanj', 'Sub-district', 56);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (446, 'Gajaria', 'Sub-district', 56);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (447, 'Tongibari', 'Sub-district', 56);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (448, 'Rajbari Sadar', 'Sub-district', 57);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (449, 'Goalanda', 'Sub-district', 57);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (450, 'Pangsa', 'Sub-district', 57);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (451, 'Baliakandi', 'Sub-district', 57);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (452, 'Kalukhali', 'Sub-district', 57);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (453, 'Madaripur Sadar', 'Sub-district', 58);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (454, 'Shibchar', 'Sub-district', 58);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (455, 'Kalkini', 'Sub-district', 58);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (456, 'Rajoir', 'Sub-district', 58);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (457, 'Gopalganj Sadar', 'Sub-district', 59);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (458, 'Kashiani', 'Sub-district', 59);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (459, 'Tungipara', 'Sub-district', 59);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (460, 'Kotalipara', 'Sub-district', 59);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (461, 'Muksudpur', 'Sub-district', 59);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (462, 'Faridpur Sadar', 'Sub-district', 60);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (463, 'Alfadanga', 'Sub-district', 60);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (464, 'Boalmari', 'Sub-district', 60);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (465, 'Sadarpur', 'Sub-district', 60);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (466, 'Nagarkanda', 'Sub-district', 60);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (467, 'Bhanga', 'Sub-district', 60);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (468, 'Charbhadrasan', 'Sub-district', 60);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (469, 'Madhukhali', 'Sub-district', 60);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (470, 'Saltha', 'Sub-district', 60);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (471, 'Panchagarh Sadar', 'Sub-district', 61);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (472, 'Debiganj', 'Sub-district', 61);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (473, 'Boda', 'Sub-district', 61);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (474, 'Atwari', 'Sub-district', 61);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (475, 'Tetulia', 'Sub-district', 61);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (476, 'Nawabganj', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (477, 'Birganj', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (478, 'Ghoraghat', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (479, 'Birampur', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (480, 'Parbatipur', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (481, 'Bochaganj', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (482, 'Kaharol', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (483, 'Fulbari', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (484, 'Dinajpur Sadar', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (485, 'Hakimpur', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (486, 'Khansama', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (487, 'Birol', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (488, 'Chirirbandar', 'Sub-district', 62);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (489, 'Lalmonirhat Sadar', 'Sub-district', 63);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (490, 'Kaliganj', 'Sub-district', 63);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (491, 'Hatibandha', 'Sub-district', 63);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (492, 'Patgram', 'Sub-district', 63);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (493, 'Aditmari', 'Sub-district', 63);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (494, 'Syedpur', 'Sub-district', 64);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (495, 'Domar', 'Sub-district', 64);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (496, 'Dimla', 'Sub-district', 64);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (497, 'Jaldhaka', 'Sub-district', 64);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (498, 'Kishorganj', 'Sub-district', 64);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (499, 'Nilphamari Sadar', 'Sub-district', 64);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (500, 'Sadullapur', 'Sub-district', 65);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (501, 'Gaibandha Sadar', 'Sub-district', 65);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (502, 'Palashbari', 'Sub-district', 65);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (503, 'Saghata', 'Sub-district', 65);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (504, 'Gobindaganj', 'Sub-district', 65);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (505, 'Sundarganj', 'Sub-district', 65);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (506, 'Phulchari', 'Sub-district', 65);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (507, 'Thakurgaon Sadar', 'Sub-district', 66);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (508, 'Pirganj', 'Sub-district', 66);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (509, 'Ranisankail', 'Sub-district', 66);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (510, 'Haripur', 'Sub-district', 66);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (511, 'Baliadangi', 'Sub-district', 66);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (512, 'Rangpur Sadar', 'Sub-district', 67);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (513, 'Gangachara', 'Sub-district', 67);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (514, 'Taragonj', 'Sub-district', 67);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (515, 'Badargonj', 'Sub-district', 67);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (516, 'Mithapukur', 'Sub-district', 67);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (517, 'Pirgonj', 'Sub-district', 67);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (518, 'Kaunia', 'Sub-district', 67);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (519, 'Pirgacha', 'Sub-district', 67);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (520, 'Kurigram Sadar', 'Sub-district', 68);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (521, 'Nageshwari', 'Sub-district', 68);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (522, 'Bhurungamari', 'Sub-district', 68);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (523, 'Phulbari', 'Sub-district', 68);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (524, 'Rajarhat', 'Sub-district', 68);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (525, 'Ulipur', 'Sub-district', 68);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (526, 'Chilmari', 'Sub-district', 68);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (527, 'Rowmari', 'Sub-district', 68);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (528, 'Charrajibpur', 'Sub-district', 68);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (529, 'Sherpur Sadar', 'Sub-district', 69);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (530, 'Nalitabari', 'Sub-district', 69);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (531, 'Sreebordi', 'Sub-district', 69);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (532, 'Nokla', 'Sub-district', 69);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (533, 'Jhenaigati', 'Sub-district', 69);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (534, 'Fulbaria', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (535, 'Trishal', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (536, 'Bhaluka', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (537, 'Muktagacha', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (538, 'Mymensingh Sadar', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (539, 'Dhobaura', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (540, 'Phulpur', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (541, 'Haluaghat', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (542, 'Gouripur', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (543, 'Gafargaon', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (544, 'Iswarganj', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (545, 'Nandail', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (546, 'Tarakanda', 'Sub-district', 70);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (547, 'Jamalpur Sadar', 'Sub-district', 71);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (548, 'Melandah', 'Sub-district', 71);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (549, 'Islampur', 'Sub-district', 71);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (550, 'Dewangonj', 'Sub-district', 71);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (551, 'Sarishabari', 'Sub-district', 71);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (552, 'Madarganj', 'Sub-district', 71);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (553, 'Bokshiganj', 'Sub-district', 71);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (554, 'Barhatta', 'Sub-district', 72);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (555, 'Durgapur', 'Sub-district', 72);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (556, 'Kendua', 'Sub-district', 72);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (557, 'Atpara', 'Sub-district', 72);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (558, 'Madan', 'Sub-district', 72);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (559, 'Khaliajuri', 'Sub-district', 72);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (560, 'Kalmakanda', 'Sub-district', 72);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (561, 'Mohongonj', 'Sub-district', 72);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (562, 'Purbadhala', 'Sub-district', 72);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (563, 'Netrokona Sadar', 'Sub-district', 72);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (564, 'Eidgaon', 'Sub-district', 17);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (565, 'Madhyanagar', 'Sub-district', 47);
INSERT INTO region (region_id, region_name, region_type, parent_region_id) VALUES (566, 'Dasar', 'Sub-district', 58);

-- Re-seed patients to map to new region IDs
TRUNCATE TABLE diseasealert;
TRUNCATE TABLE regionalaggregate;
TRUNCATE TABLE healthscore;
TRUNCATE TABLE observation;
TRUNCATE TABLE diagnosis;
TRUNCATE TABLE patient;
INSERT INTO patient (patient_id, region_id, full_name, date_of_birth, gender, blood_group, phone) VALUES 
(1, 73, 'Abdur Rahman', '1985-04-12', 'Male', 'O+', '01711223344'),
(2, 74, 'Fatima Begum', '1992-08-25', 'Female', 'A+', '01822334455'),
(3, 75, 'Kamal Hossain', '1978-11-05', 'Male', 'B-', '01933445566'),
(4, 76, 'Nusrat Jahan', '2001-02-14', 'Female', 'AB+', '01544556677'),
(5, 77, 'Sakib Hasan', '1995-07-30', 'Male', 'O-', '01655667788');
INSERT INTO observation (patient_id, loinc_code_id, observation_value, unit, observation_datetime) VALUES
(1, 1, 36.8, 'C', NOW() - INTERVAL 1 DAY),
(1, 2, 98, '%', NOW() - INTERVAL 1 DAY),
(1, 3, 120, 'mmHg', NOW() - INTERVAL 1 DAY),
(1, 4, 75, 'beats/min', NOW() - INTERVAL 1 DAY),
(2, 1, 38.5, 'C', NOW() - INTERVAL 2 HOUR),
(2, 2, 91, '%', NOW() - INTERVAL 2 HOUR),
(2, 3, 105, 'mmHg', NOW() - INTERVAL 2 HOUR),
(2, 4, 115, 'beats/min', NOW() - INTERVAL 2 HOUR),
(3, 1, 37.1, 'C', NOW() - INTERVAL 5 HOUR),
(3, 2, 97, '%', NOW() - INTERVAL 5 HOUR),
(3, 3, 160, 'mmHg', NOW() - INTERVAL 5 HOUR),
(3, 4, 88, 'beats/min', NOW() - INTERVAL 5 HOUR),
(5, 1, 39.2, 'C', NOW() - INTERVAL 1 HOUR),
(5, 2, 88, '%', NOW() - INTERVAL 1 HOUR),
(5, 3, 85, 'mmHg', NOW() - INTERVAL 1 HOUR),
(5, 4, 130, 'beats/min', NOW() - INTERVAL 1 HOUR);
INSERT INTO healthscore (patient_id, score_datetime, respiratory_score, oxygen_score, systolic_bp_score, pulse_score, temperature_score, consciousness_score, total_score, risk_level) VALUES
(1, NOW() - INTERVAL 1 DAY, 0, 0, 0, 0, 0, 0, 0, 'Low'),
(2, NOW() - INTERVAL 2 HOUR, 1, 3, 0, 1, 1, 0, 6, 'High'),
(3, NOW() - INTERVAL 5 HOUR, 0, 0, 1, 0, 0, 0, 1, 'Low'),
(5, NOW() - INTERVAL 1 HOUR, 2, 3, 3, 2, 2, 0, 12, 'Critical');
SET FOREIGN_KEY_CHECKS = 1;